package org.team3128;

/*
 * THIS FILE SHOULD NOT BE MODIFIED
 * --------------------------------
 * It serves as a link to the Global class
 * Events triggered here will be forwarded to the Global class
 * This will also invoke the EventManager's sequencing.
 *
 * Do not call these functions under any circumstances. Do not modify this
 * class under any circumstances.
 *
 * AUTOGENERATED. DO NOT EDIT UNDER PENALTY OF 42.
 *
 * THIS FILE IS YOUR SOUL.
 */

public class RobotTemplate {
    public void robotInit()
    {
    	
    }

    public void disabledInit()
    {
    	
    }

    public void autonomousInit()
    {
    	
    }
   
    public void teleopInit()
    {

    }
   
    public void disabledPeriodic()
    {
        
    }
   
    public void autonomousPeriodic() 
    {
    	
    }
   
    public void teleopPeriodic()
    {
    	
    }
    }

